import { mkdir, readdir, rm, writeFile } from 'node:fs/promises';
import { basename, extname, join } from 'node:path';
import sharp from 'sharp';

/**
 * Build time image pipeline, per tech.md section 2: sharp, AVIF plus WebP, srcset, no
 * external CDN. Sources live in assets/images and never ship. Derivatives land in
 * static/img and the manifest lands in src/lib/content/generated/images.ts, both
 * committed so `pnpm build` stays a pure compile and CI does not need sharp.
 *
 * Run it after replacing a source photograph: `pnpm images`.
 */

const SOURCE_DIR = 'assets/images';
const OUTPUT_DIR = 'static/img';
const MANIFEST = 'src/lib/content/generated/images.ts';

// 360 px is the narrowest supported viewport, 1920 the widest sensible hero. Anything
// between is covered by the browser picking the next step up.
const WIDTHS = [480, 768, 1080, 1440, 1920];

interface Variant {
	format: 'avif' | 'webp' | 'jpeg';
	extension: 'avif' | 'webp' | 'jpg';
}

const VARIANTS: Variant[] = [
	{ format: 'avif', extension: 'avif' },
	{ format: 'webp', extension: 'webp' },
	{ format: 'jpeg', extension: 'jpg' }
];

interface ManifestEntry {
	width: number;
	height: number;
	avif: string;
	webp: string;
	jpeg: string;
	fallback: string;
}

async function encode(
	source: string,
	name: string,
	width: number,
	variant: Variant
): Promise<string> {
	const file = `${name}-${width}.${variant.extension}`;
	const pipeline = sharp(source).resize({ width, withoutEnlargement: true });
	// AVIF earns its slow encode here: the files are built once and served forever.
	if (variant.format === 'avif') await pipeline.avif({ quality: 52, effort: 6 }).toFile(join(OUTPUT_DIR, file));
	if (variant.format === 'webp') await pipeline.webp({ quality: 74 }).toFile(join(OUTPUT_DIR, file));
	if (variant.format === 'jpeg') await pipeline.jpeg({ quality: 78, mozjpeg: true }).toFile(join(OUTPUT_DIR, file));
	return `/img/${file} ${width}w`;
}

async function run(): Promise<void> {
	await rm(OUTPUT_DIR, { recursive: true, force: true });
	await mkdir(OUTPUT_DIR, { recursive: true });

	const sources = (await readdir(SOURCE_DIR))
		.filter((file) => ['.jpg', '.jpeg', '.png'].includes(extname(file).toLowerCase()))
		.sort();

	const manifest: Record<string, ManifestEntry> = {};

	for (const file of sources) {
		const source = join(SOURCE_DIR, file);
		const name = basename(file, extname(file));
		const meta = await sharp(source).metadata();
		if (!meta.width || !meta.height) throw new Error(`${file} has no dimensions`);

		// Never upscale: a small source produces fewer steps rather than blurry ones.
		const widths = WIDTHS.filter((width) => width <= meta.width!);
		if (widths.length === 0) widths.push(meta.width);

		const srcset: Record<string, string[]> = { avif: [], webp: [], jpeg: [] };
		for (const width of widths) {
			for (const variant of VARIANTS) {
				srcset[variant.format].push(await encode(source, name, width, variant));
			}
		}

		const largest = widths[widths.length - 1];
		manifest[name] = {
			width: meta.width,
			height: meta.height,
			avif: srcset.avif.join(', '),
			webp: srcset.webp.join(', '),
			jpeg: srcset.jpeg.join(', '),
			// The <img> fallback stays mid sized: it only loads where AVIF and WebP both fail.
			fallback: `/img/${name}-${widths[Math.min(widths.length - 1, 2)]}.jpg`
		};
		console.log(`${name}: ${widths.length} widths x ${VARIANTS.length} formats`);
	}

	const body = `// Generated by scripts/images.ts. Run \`pnpm images\` after changing assets/images.
// Committed on purpose: the build compiles, it does not re-encode.

export interface ImageAsset {
	width: number;
	height: number;
	avif: string;
	webp: string;
	jpeg: string;
	fallback: string;
}

export const images = ${JSON.stringify(manifest, null, '\t')} as const satisfies Record<string, ImageAsset>;

export type ImageName = keyof typeof images;
`;
	await writeFile(MANIFEST, body, 'utf8');
	console.log(`manifest: ${Object.keys(manifest).length} images`);
}

await run();
